### ISSUE TITLE
[BUG]ヘッダのResourcesリンクを押すとmediumのページで404となる

### ISSUE THREAD

**Issue by hirofumimatsu** [getunid/unid-docs#5]
**Describe the bug**
ヘッダのResourcesリンクを押すとmediumのページで404となる

**To Reproduce**
1. Go to 'https://docs.getunid.io/'
2. Click on 'Resources'
3. See 404 error on medium.

**Expected behavior**
no 404 error.

**Screenshots**
<img width="2470" alt="スクリーンショット 2021-06-09 1 06 55" src="https://user-images.githubusercontent.com/10016898/121219786-0437b300-c8bf-11eb-8452-7b7ecc690b72.png">

**Desktop (please complete the following information):**
 - OS: macos 
 - Browser : chrome
 - Version バージョン: 91.0.4472.77（Official Build） （x86_64）

**Comment by masa256k1** [comment]
Hi @hirofumimatsu 

Fixed the medium link. Thank you for the feedback!
